#!/usr/bin/env bash
#
# Build the md4c FFI shim into a platform-native shared library, and (re)generate
# the FFI scope header (md4cshim.h) with an absolute FFI_LIB path so the
# opcache.preload fast-path (FFI::load) binds the right file wherever the repo
# lives. Produces:
#   - macOS : libmd4cshim.dylib
#   - Linux : libmd4cshim.so
#   - Win   : md4cshim.dll   (mingw/msys)
#
# Usage:  native/build.sh        (or: CC=gcc native/build.sh)
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

# Pick a C compiler: $CC, then cc, clang, gcc.
CC="${CC:-cc}"
command -v "$CC" >/dev/null 2>&1 || CC=clang
command -v "$CC" >/dev/null 2>&1 || CC=gcc
command -v "$CC" >/dev/null 2>&1 || { echo "error: no C compiler (cc/clang/gcc) found" >&2; exit 1; }

case "$(uname -s)" in
  Darwin)               LIBNAME="libmd4cshim.dylib" ;;
  Linux)                LIBNAME="libmd4cshim.so" ;;
  MINGW*|MSYS*|CYGWIN*) LIBNAME="md4cshim.dll" ;;
  *)                    LIBNAME="libmd4cshim.so" ;;
esac

SOURCES=(shim.c md4c/md4c.c md4c/md4c-html.c md4c/entity.c)

echo "==> Compiling $LIBNAME  ($CC -O3 -flto -pthread)"
"$CC" -O3 -flto -fPIC -shared -DNDEBUG -pthread -o "$LIBNAME" "${SOURCES[@]}"

echo "==> Symbols:"
if command -v nm >/dev/null 2>&1; then
  # ' T _?md2html' matches defined text symbols on both BSD/macOS and GNU nm
  # (macOS prefixes an underscore). $NF is the symbol name.
  nm -g "$LIBNAME" 2>/dev/null | awk '/ T _?md2html/{print "      "$NF}' | sort -u || true
fi

# Regenerate the FFI scope header with THIS machine's absolute lib path.
cat > md4cshim.h <<EOF
/* GENERATED by native/build.sh — do not edit by hand.
 * FFI scope header for the opcache.preload (FFI::load) fast path. */
#define FFI_SCOPE "MD4C"
#define FFI_LIB "$DIR/$LIBNAME"
char* md2html(const char* input, size_t input_len, size_t* out_len, unsigned int parser_flags, unsigned int renderer_flags);
void md2html_free(char* p);
unsigned int md2html_dialect_github(void);
char* md2html_batch(const char* packed, const size_t* in_offsets, size_t n, size_t* out_offsets, unsigned int parser_flags, unsigned int renderer_flags, int threads);
EOF

echo "==> Wrote md4cshim.h  (FFI_LIB=$DIR/$LIBNAME)"
echo "==> Done."
